# Generated by Django 2.0.3 on 2018-03-31 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandlistmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='band',
        ),
        migrations.AddField(
            model_name='bands',
            name='members',
            field=models.ManyToManyField(null=True, to='bandlistmaker.Members'),
        ),
        migrations.AddField(
            model_name='bands',
            name='seasons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bandlistmaker.Seasons'),
        ),
    ]
