# Generated by Django 2.0.3 on 2018-04-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandlistmaker', '0002_auto_20180331_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bands',
            name='seasons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bandlistmaker.Seasons'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
