# Generated by Django 2.0.3 on 2018-04-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandlistmaker', '0004_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='bands',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bands',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='bandlistmaker.Members'),
        ),
        migrations.AlterField(
            model_name='bands',
            name='seasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bandlistmaker.Seasons'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
